* A
** Audacity
   meaning:
   aggressive boldness or unmitigated effrontery
   If you have audacity the you are one daring and perhaps reckless character.
   Someone who shows audacity makes bold moves and is not afraid of consequences.
   *Sentence:*
   Audacity can be frowned upon depending upon how far it's taken and how it
   rears its head.
   Success is the child of audacity.

* F
** Figure of speech
   *Meaning:*
   A figure of speech is a phrase or saying that's not literal like saying
   someone who died "kicked the butt".
   When you say you are hungry enough to eat a horse; its doubtful that you mean
   that literally; its just a figure of speech.
   When you are saying its raining cats and dogs, pets are not falling from the
   sky: its figure of speech.
   *Sentence:*
   You have people who are eating mud and I don't mean that as figure of
   speech.
* C
** conjure
   meaning:
   summon into action or bring into existence often by magic
   Sentence:
   
** Crunch Time: period of time just before a project has to completed and 
   everyone has to work hard. 
   1. I am not getting enough sleep these days. Its crunch time at work.
   2. 
** Cut somebody some slack: to give somebody a break/ not to judge somebody severly.
   1. I was extremely busy last week. Cut me some slack and I will finish the
      report by tomorrow.
** Condescending
   *Meaning*
   If you are being consdescending, you are looking down on
   someone. Condescending behavior is, not surprisingly, itself looked down
   upon. It is usullay intended to make people feel bad about not knowing or
   having something, and it very often works.
   *Sentence*
   Its a little condescending. 
** Conjure
   *Meaning*
   bring into existence often magically
* D
** Dig in your heels: refuse to compromise or change your mind
   1. My parents wanted me to give up writing, but i dug in my heels and went on
      to become a famous writer.
** Detrimental
   *Meaning*
   *formal* way of saying harmful, damaging.
   *Sentence*
   detrimental to health.
* G
** go the extra mile: to make special effort/ try very hard to acheive goal
   1. If you want to become proficient in English, you'll have to go the extra
      mile and start learnign idioms.
* H
** Hobble
   meaning: walk in awkward way.
* L
** Let your freak flag fly: to let others see your uniqueness.
   1. My colleagues were surprised at the Christmas party-I let my freak flag
      fly and showed them a break dance routine
* M
** Metaphor(n)
   meaning:
   a figure of speech in which an expression is used to refer to something that
   it does not literally denote in order to suggest a similarity.
* T
** Tenuous
   meaning: 
   If something is tenuous it is thin either literally or
   metaphorically.
   lacking substance of significance
   Something can be physically tenuous like spider web, or ice on pond. We more
   often use in metaphorical sense, to talk about weak ideas.
   Sentence:
   1. If you try to learn a complex mathematical subject in few hours you will
      have *tenuous* grasp of it.
   2. We will discover how to from compound data using no special data operation
      at all only procedures. This will further blur the distinction between
      data and procedure which was becoming *tenuous* toward the end of chapter.
   3. *tenuous* argument won't win any debate tournaments.
** Transgression
   *Meaning:*
   Something against a command or law. Wether you are cheating on a test, or
   cheating on a spouse, you are committing transgressions that are not easily
   forgiven. 
   *Sentence*
   Your trangressions will not overlooked. You should be held accountable.
* P
** plug
   *Meaning:*
   A plug is something that blocks a hole. It also means to promote something.
   If you plug your new book, you sneak it into every conversation.
   *Sentence*
*** pull the plug
    informal
    prevent something from happening or continuing
    *Sentence*
    The company pulled the plug one the deal.
    
** pull your self together: to calm down and behave normally
   1. I understand you've had a bad day, but pull yourself together and get on
      with your job, will you?

** plug a hole
   *meaning*
   to fix a recurring problem
   *Sentence*
   Blue house tries to plug the holes in PR machine.

* R
** rear its ugly head(figure of speech)
   meaning: [for something unpleasant] to appear or become obvious after lying
   hidden.
   *Sentence*: The interview went very well until a question about his academic
   record reared its ugly head.

* S
** Stick to your guns: to refuse to compromise or change your mind.
   1. My parents wanted to give up writing, but I stuck to my guns and went on
      to become famous writer.
   2. 
** step up your game: to start performing better
   1. if you want to win competetion, you will have to step up your game.

** shape up or ship out: either start performing better or leave.
   This is the last time I am telling you to arrive on time. Shape up or ship out.
** shoot from the hip: to speak directly
   1. If you want to get on well with your boss try not to shoot from the hip
      next time. You don't want to offend him, do you?

* U
** Upheaval
   meaning:
   a violent disturbance

** sneak
** stealth

